name = "do-worker"
main = "src/index.ts"
compatibility_date = "2026-01-20"


[[kv_namespaces]]
binding = "EXAMPLE_KV"
id = "preview-id"
preview_id = "preview-id"

[[durable_objects.bindings]]
name = "MY_DO"
class_name = "DurableObjectClass"
